打包镜像时 ollama 改用宿主机

diff --git a/Dockerfile-ollama-local b/Dockerfile-ollama-local
--- a/Dockerfile-ollama-local
+++ b/Dockerfile-ollama-local
@@ -25,26 +25,26 @@ RUN apt-get update && apt-get install -y \
     curl
 # Detect architecture and download appropriate Ollama version
 # ARG TARGETARCH can be set at build time with --build-arg TARGETARCH=arm64 or TARGETARCH=amd64
-ARG TARGETARCH=arm64
-RUN OLLAMA_ARCH="" && \
-    if [ "$TARGETARCH" = "arm64" ]; then \
-        echo "Building for ARM64 architecture." && \
-        OLLAMA_ARCH="arm64"; \
-    elif [ "$TARGETARCH" = "amd64" ]; then \
-        echo "Building for AMD64 architecture." && \
-        OLLAMA_ARCH="amd64"; \
-    else \
-        echo "Error: Unsupported architecture '$TARGETARCH'. Supported architectures are 'arm64' and 'amd64'." >&2 && \
-        exit 1; \
-    fi && \
-    curl -L "https://ollama.com/download/ollama-linux-${OLLAMA_ARCH}.tgz" -o ollama.tgz && \
-    tar -C /usr -xzf ollama.tgz && \
-    rm ollama.tgz
+# ARG TARGETARCH=arm64
+# RUN OLLAMA_ARCH="" && \
+#     if [ "$TARGETARCH" = "arm64" ]; then \
+#         echo "Building for ARM64 architecture." && \
+#         OLLAMA_ARCH="arm64"; \
+#     elif [ "$TARGETARCH" = "amd64" ]; then \
+#         echo "Building for AMD64 architecture." && \
+#         OLLAMA_ARCH="amd64"; \
+#     else \
+#         echo "Error: Unsupported architecture '$TARGETARCH'. Supported architectures are 'arm64' and 'amd64'." >&2 && \
+#         exit 1; \
+#     fi && \
+#     curl -L "https://ollama.com/download/ollama-linux-${OLLAMA_ARCH}.tgz" -o ollama.tgz && \
+#     tar -C /usr -xzf ollama.tgz && \
+#     rm ollama.tgz
 
-RUN ollama serve > /dev/null 2>&1 & \
-    sleep 20 && \
-    ollama pull nomic-embed-text && \
-    ollama pull qwen3:1.7b
+# RUN ollama serve > /dev/null 2>&1 & \
+#     sleep 20 && \
+#     ollama pull nomic-embed-text && \
+#     ollama pull qwen3:1.7b
 
 # Use Python 3.11 as final image
 FROM python:3.11-slim
@@ -75,8 +75,8 @@ COPY api/ ./api/
 COPY --from=node_builder /app/public ./public
 COPY --from=node_builder /app/.next/standalone ./
 COPY --from=node_builder /app/.next/static ./.next/static
-COPY --from=ollama_base /usr/bin/ollama /usr/local/bin/
-COPY --from=ollama_base /root/.ollama /root/.ollama
+# COPY --from=ollama_base /usr/bin/ollama /usr/local/bin/
+# COPY --from=ollama_base /root/.ollama /root/.ollama
 
 # Expose the port the app runs on
 EXPOSE ${PORT:-8001} 3000
@@ -84,7 +84,7 @@ EXPOSE ${PORT:-8001} 3000
 # Create a script to run both backend and frontend
 RUN echo '#!/bin/bash\n\
 # Start ollama serve in background\n\
-ollama serve > /dev/null 2>&1 &\n\
+# ollama serve > /dev/null 2>&1 &\n\
 \n\
 # Load environment variables from .env file if it exists\n\
 if [ -f .env ]; then\n\
